### ISSUE TITLE
Insert Value from Previous Relation Index

### ISSUE THREAD

**Issue by indowebdeveloper** [czim/laravel-nestedupdater#4]
Hi there, first of all i'd like to say thankyou for the developer who created this, it really helps me..

Now, i have some issue since i cant find the docs related to my issue.

Lets say i have these relation hierarchy

DeliveryLists > DeliveryListItems > DeliveryListItemVariants

My question is,
How to insert the id of DeliveryLists into the DeliveryListItemVariants ? since what we need to do is only post the data into the DeliveryLists creation / update right ?

Hope anyone can help my issue here
Thankyou Very much

**Comment by czim** [comment]
Hello, and you're welcome.

Can you specify your specific use-case a bit further?

The updater is designed to automatically connect new nested child elements to the parent. It should automatically inject the correct foreign keys, as long as your model relations are defined right. The same goes for (re)connecting models by ID for BelongsToMany relations.

**Comment by indowebdeveloper** [comment]
Hello czim, thankyou for answering

So here is my case..

I have a delivery list , the delivery list is contain a multiple Items, and one item is containing a multiple item variation..

For example i create a delivery list..

ITEM A <--- its called Items
============
Color Red <-- its called ItemVariants
Color Blue

so i'm just wondering, is that possible to insert the DeliveryList id into the ItemVariants model ? I understand if its about the Items id on the ItemVariants would be no problem.. 

So just wondering is that possible to insert the created DeliveryList id into the ItemVariants just like into the Items model..

Thankyou so much.. :D

**Comment by indowebdeveloper** [comment]
But i think i already solve my issue by just using HasManyThrough relation, because my actual goal is for listing all DeliveryItemVariants based on DeliveryList..

But just still wondering if my question is still possible to be done or not, in case i facing something similiar in the future which not allow me to use hasmanythrough relation..

Thanks again.. :D
